// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MeasurementDbContext))]
    partial class MeasurementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.MeasurementEntity", b =>
                {
                    b.Property<string>("AquariumId")
                        .HasColumnType("text")
                        .HasColumnName("aquarium_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<decimal?>("Ca")
                        .HasColumnType("numeric")
                        .HasColumnName("ca");

                    b.Property<decimal?>("Kh")
                        .HasColumnType("numeric")
                        .HasColumnName("kh");

                    b.Property<decimal?>("Mg")
                        .HasColumnType("numeric")
                        .HasColumnName("mg");

                    b.Property<decimal?>("Oxygen")
                        .HasColumnType("numeric")
                        .HasColumnName("oxygen");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("numeric")
                        .HasColumnName("ph");

                    b.Property<decimal?>("Pump")
                        .HasColumnType("numeric")
                        .HasColumnName("pump");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature");

                    b.HasKey("AquariumId", "Timestamp");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_measurements_timestamp");

                    b.HasIndex("AquariumId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_measurements_aquarium_timestamp_desc");

                    b.ToTable("measurements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
